version: '3.12'
services:
    server:
        container_name: cls_fastapi
        hostname: cls_server
        build:
          context: ./server
        depends_on:
          - postgres
        env_file:
          - ./.env
        ports:
          - 8000:8000
        volumes:
          - ./server:/var/www/html
        networks:
          - cls-net
        restart: unless-stopped
    postgres:
        container_name: cls_postgres
        image: postgres:15
        hostname: cls_postgres
        environment:
          - POSTGRES_DB=${POSTGRES_DB}
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        logging:
          driver: "json-file"
          options:
            max-size: "200K"
            max-file: "10"
        ports:
          - ${POSTGRES_PORT_HOST}:${POSTGRES_PORT_DOCKER}
        volumes:
          - ./data/postgres:/var/lib/postgresql/data
          - ./data/share:/share
        networks:
          - cls-net

    redis:
        image: redis:7-alpine
        container_name: cls_redis
        hostname: cls_redis
        ports:
          - "6379:6379"
        volumes:
          - ./data/redis:/data
        networks:
          - cls-net

    worker:
        build:
          context: ./server
        container_name: cls_worker
        hostname: cls_worker
        command: bash -c "rq worker-pool -n 16 tasks"
        deploy:
          resources:
            limits:
              memory: 32G
        volumes:
          - ./server:/var/www/html
        depends_on:
          - postgres
          - redis
        env_file:
          - ./.env
        environment:
          - REDIS_URL=redis://redis:6379/0
          - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT_DOCKER}/${POSTGRES_DB}
        networks:
          - cls-net
        restart: unless-stopped
    client:
        container_name: cls_client
        hostname: client
        build:
          context: ./client
        environment:
          - APP_CLIENT_PORT=3000
        ports:
          - "3005:3000"
        volumes:
          - ./client:/usr/src/app
        networks:
          - cls-net

networks:
  cls-net:
    driver: bridge
